# Generated by Django 6.0.7 on 2026-07-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('columns', models.JSONField()),
                ('records', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
