# Generated by Django 6.0.7 on 2026-07-28 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_equivalenceconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMeansRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_count', models.PositiveSmallIntegerField()),
                ('selected_columns', models.JSONField()),
                ('assignments', models.JSONField()),
                ('centroids', models.JSONField()),
                ('cluster_sizes', models.JSONField()),
                ('imputed_values', models.JSONField(default=dict)),
                ('sample_count', models.PositiveIntegerField()),
                ('inertia', models.FloatField()),
                ('silhouette', models.FloatField(blank=True, null=True)),
                ('silhouette_sample_count', models.PositiveIntegerField(default=0)),
                ('category_filter', models.CharField(blank=True, max_length=255)),
                ('category_label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kmeans_runs', to='datasets.dataset')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
