# Generated by Django 6.0.7 on 2026-07-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmeansrun',
            name='cluster_comparison',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='kmeansrun',
            name='comparison_column',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kmeansrun',
            name='comparison_valid_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kmeansrun',
            name='comparison_values',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='kmeansrun',
            name='overall_match_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
