# Generated by Django 6.0.7 on 2026-08-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0009_kmeans_methodology_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmeansrun',
            name='cluster_category_association',
        ),
        migrations.RemoveField(
            model_name='kmeansrun',
            name='contingency_matrix',
        ),
        migrations.RemoveField(
            model_name='kmeansrun',
            name='external_metrics',
        ),
        migrations.RemoveField(
            model_name='kmeansrun',
            name='quality_warnings',
        ),
        migrations.RemoveField(
            model_name='kmeansrun',
            name='recommended_k_elbow',
        ),
        migrations.RemoveField(
            model_name='kmeansrun',
            name='recommended_k_silhouette',
        ),
        migrations.RemoveField(
            model_name='kmeansrun',
            name='results_by_k',
        ),
        migrations.RemoveField(
            model_name='kmeansrun',
            name='selected_k',
        ),
        migrations.RemoveField(
            model_name='kmeansrun',
            name='stability_metrics',
        ),
    ]
