# Generated by Django 6.0.7 on 2026-07-31 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_equivalenceconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchicalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_clusters', models.IntegerField(default=2)),
                ('linkage', models.CharField(default='ward', max_length=50)),
                ('affinity', models.CharField(default='euclidean', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchical_runs', to='datasets.dataset')),
            ],
        ),
    ]
