# Generated by Django 6.0.7 on 2026-07-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hierarchicalrun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='dendrogram_image',
            field=models.ImageField(blank=True, null=True, upload_to='hierarchical/dendrograms/'),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='scaling_method',
            field=models.CharField(blank=True, default='standard', help_text='Ej: standard, minmax, none', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='silhouette_score',
            field=models.FloatField(blank=True, help_text='Métrica de evaluación (de -1 a 1)', null=True),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='affinity',
            field=models.CharField(default='euclidean', help_text='Métrica de distancia usada', max_length=50),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='linkage',
            field=models.CharField(default='ward', help_text='Criterio de enlace (ward, complete, average, single)', max_length=50),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='n_clusters',
            field=models.IntegerField(default=2, help_text='Número de clústeres a encontrar'),
        ),
    ]
