# Generated by Django 6.0.7 on 2026-07-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchical', '0002_alter_hierarchicalrun_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierarchicalrun',
            name='dendrogram_image',
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='cluster_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='comparison_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='sample_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='selected_columns',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='affinity',
            field=models.CharField(default='euclidean', max_length=50),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='linkage',
            field=models.CharField(default='ward', max_length=50),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='n_clusters',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='scaling_method',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='silhouette_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
