# Generated by Django 6.0.7 on 2026-07-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchical', '0003_remove_hierarchicalrun_dendrogram_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchicalrun',
            name='assignments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='cluster_comparison',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='cluster_sizes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='comparison_valid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='comparison_values',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='overall_match_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
