# Generated by Django 6.0.7 on 2026-07-31 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0002_equivalenceconfiguration_and_more'),
        ('hierarchical', '0004_hierarchicalrun_assignments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hierarchicalrun',
            options={'ordering': ('-activated_at', '-created_at')},
        ),
        migrations.RemoveField(
            model_name='hierarchicalrun',
            name='silhouette_score',
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='activated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='category_column',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='category_filter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='category_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='change_summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='dataset_fingerprint',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='dataset_schema_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='dataset_source_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='estimator_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='imputed_values',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='library_versions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='new_record_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='parent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrained_versions', to='hierarchical.hierarchicalrun'),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='preprocessing_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='schema_profile',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='silhouette',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='silhouette_sample_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='source_row_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='topic',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='training_config_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hierarchicalrun',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='cluster_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='comparison_column',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='comparison_valid_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hierarchical_runs', to='datasets.dataset'),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='n_clusters',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='hierarchicalrun',
            name='sample_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
