# Generated by Django 6.0.7 on 2026-08-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbscan', '0007_dbscanrun_dynamic_category_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbscanrun',
            name='pca_components',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dbscanrun',
            name='use_pca',
            field=models.BooleanField(default=False),
        ),
    ]
